image: haskell:9.2.1

pipelines:
  default:
    - step:
        caches:
          - stack
          - stack-root
        name: Build and test
        script:
          - apt-get update && apt-get install -y libssl-dev build-essential
          - make all
    - step:
        caches:
          - stack
          - stack-root
        name: Test source distribution
        script:
          - apt-get update && apt-get install -y libssl-dev build-essential
          - make test-dist

definitions:
  caches:
    stack: ~/.stack-work
    stack-root: /root/.stack
